-- CreateEnum
CREATE TYPE "UserPermission" AS ENUM ('MANAGE_USERS', 'MANAGE_LISTINGS', 'MANAGE_BOATS', 'MANAGE_CATEGORIES', 'MANAGE_CONTENT', 'MANAGE_BANNERS', 'MANAGE_SUBSCRIPTIONS', 'MANAGE_SELLERS', 'MANAGE_SETTINGS', 'VIEW_DASHBOARD', 'MANAGE_FEATURED_BRANDS', 'MANAGE_CONTACT');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "permissions" "UserPermission"[] DEFAULT ARRAY[]::"UserPermission"[];
